### PR TITLE
Remove occurrences of Goll_m

### PR DESCRIPTION
**Pull request by mfranciszkiewicz**

### CODE REVIEW

**Review by Wiezzel — APPROVED** [review]
XD

**Review by maaktweluit — APPROVED** [review]
What is wrong with `Goll_m`?

**Comment by Wiezzel** [comment]
@maaktweluit We have an agreement that specifically forbids us to use this name.

**Comment by maaktweluit** [comment]
Ahh, its on the list ;) thanks :)

**Pull request merged**
